# Generated by Django 4.0.2 on 2022-02-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220115_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Deseos',
        ),
    ]
